version: 0.0
phases:
  install:
    commands:
      - echo "No installation steps required for this simple HTML project"  # Optional informative message
  build:
    commands:
      - cp index.html $CODEBUILD_OUTPUT_DIR/  # Copy HTML file
      - cp profile-pic.jpg $CODEBUILD_OUTPUT_DIR/  # Copy image file (assuming it exists)
