version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
  pre_build:
    commands:
      - echo "Running pre-build steps..."
  build:
    commands:
      - echo "Building the application..."
      - cp index.html $CODEBUILD_OUTPUT_DIR/
      - cp profile-pic.jpg $CODEBUILD_OUTPUT_DIR/
  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_OUTPUT_DIR
